package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RentalOfficeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRentalOfficeAllPropertiesEquals(RentalOffice expected, RentalOffice actual) {
        assertRentalOfficeAutoGeneratedPropertiesEquals(expected, actual);
        assertRentalOfficeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRentalOfficeAllUpdatablePropertiesEquals(RentalOffice expected, RentalOffice actual) {
        assertRentalOfficeUpdatableFieldsEquals(expected, actual);
        assertRentalOfficeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRentalOfficeAutoGeneratedPropertiesEquals(RentalOffice expected, RentalOffice actual) {
        assertThat(actual)
            .as("Verify RentalOffice auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRentalOfficeUpdatableFieldsEquals(RentalOffice expected, RentalOffice actual) {
        assertThat(actual)
            .as("Verify RentalOffice relevant properties")
            .satisfies(a -> assertThat(a.getOfficeName()).as("check officeName").isEqualTo(expected.getOfficeName()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRentalOfficeUpdatableRelationshipsEquals(RentalOffice expected, RentalOffice actual) {
        assertThat(actual)
            .as("Verify RentalOffice relationships")
            .satisfies(a -> assertThat(a.getDrivers()).as("check drivers").isEqualTo(expected.getDrivers()));
    }
}
